# local 환경

server:
  port: 8080

spring:
  h2:
    console:
      enabled: true
      path: /h2

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true

  servlet:
    multipart:
      max-request-size: 2MB
      max-file-size: 2MB

logging.level:
  org.hibernate.SQL: debug
  org.hibernate.type: trace